 type: 'root',
  children: 
   [ { type: 'thematicBreak', position: [Object] },
     { type: 'paragraph', children: [Array], position: [Object] },
     { type: 'heading',
       depth: 2,
       children: [Array],
       position: [Object] },
     { type: 'paragraph', children: [Array], position: [Object] },
     { type: 'heading',
       depth: 3,
       children: [Array],
       position: [Object] },
     { type: 'paragraph', children: [Array], position: [Object] },
     { type: 'paragraph', children: [Array], position: [Object] },
     { type: 'paragraph', children: [Array], position: [Object] },
     { type: 'paragraph', children: [Array], position: [Object] },
     { type: 'list',
       ordered: false,
       start: null,
       loose: false,
       children: [Array],
       position: [Object] },
     { type: 'heading',
       depth: 3,
       children: [Array],
       position: [Object] },
     { type: 'paragraph', children: [Array], position: [Object] },
     { type: 'paragraph', children: [Array], position: [Object] },
     { type: 'paragraph', children: [Array], position: [Object] },
     { type: 'paragraph', children: [Array], position: [Object] },
     { type: 'html',
       value: '<aside>\n|- Journal is funny word. -|',
       position: [Object] },
     { type: 'paragraph', children: [Array], position: [Object] },
     { type: 'html', value: '</aside>', position: [Object] },
     { type: 'paragraph', children: [Array], position: [Object] },
     { type: 'heading',
       depth: 4,
       children: [Array],
       position: [Object] },
     { type: 'paragraph', children: [Array], position: [Object] },
     { type: 'paragraph', children: [Array], position: [Object] },
     { type: 'paragraph', children: [Array], position: [Object] },
     { type: 'html',
       value: '<aside>Whole aside into taking screenshots of dev tools from dev tools, see [tweet](https://twitter.com/davvidbaker/status/923676617842610176), ${also embed the tweet}</aside>',
       position: [Object] },
     { type: 'paragraph', children: [Array], position: [Object] },
     { type: 'paragraph', children: [Array], position: [Object] },
     { type: 'thematicBreak', position: [Object] },
     { type: 'paragraph', children: [Array], position: [Object] },
     { type: 'paragraph', children: [Array], position: [Object] },
     { type: 'paragraph', children: [Array], position: [Object] },
     { type: 'thematicBreak', position: [Object] },
     { type: 'paragraph', children: [Array], position: [Object] },
     { type: 'heading',
       depth: 1,
       children: [Array],
       position: [Object] },
     { type: 'paragraph', children: [Array], position: [Object] },
     { type: 'paragraph', children: [Array], position: [Object] },
     { type: 'paragraph', children: [Array], position: [Object] },
     { type: 'heading',
       depth: 2,
       children: [Array],
       position: [Object] },
     { type: 'paragraph', children: [Array], position: [Object] },
     { type: 'thematicBreak', position: [Object] },
     { type: 'paragraph', children: [Array], position: [Object] },
     { type: 'paragraph', children: [Array], position: [Object] },
     { type: 'paragraph', children: [Array], position: [Object] },
     { type: 'paragraph', children: [Array], position: [Object] },
     { type: 'code',
       lang: null,
       value: 'A S D F\nh t e l\nh i v a\nh t T m\n  c o e\n  h o \n    l C\n    s h\n      a\n      r\n      t',
       position: [Object] },
     { type: 'paragraph', children: [Array], position: [Object] },
     { type: 'paragraph', children: [Array], position: [Object] },
     { type: 'paragraph', children: [Array], position: [Object] },
     { type: 'paragraph', children: [Array], position: [Object] },
     { type: 'paragraph', children: [Array], position: [Object] },
     { type: 'paragraph', children: [Array], position: [Object] },
     { type: 'paragraph', children: [Array], position: [Object] },
     { type: 'paragraph', children: [Array], position: [Object] },
     { type: 'paragraph', children: [Array], position: [Object] },
     { type: 'paragraph', children: [Array], position: [Object] },
     { type: 'paragraph', children: [Array], position: [Object] } ],
  position: 
   { start: { line: 1, column: 1, offset: 0 },
     end: { line: 142, column: 1, offset: 6990 } } }